---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: weekly
      open-pull-requests-limit: 10
      allow:
        - dependency-type: "all"
      groups:
        bundler-rubocop:
          patterns:
            - "rubocop*"
        bundler-all:
          update-types:
            - minor
            - patch
          exclude-patterns:
            - "rubocop*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
